name: Test and Deploy

on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: run test
        run: npm run test
  build:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployed"
