name: Test and Deploy

on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: run lint
        run: npm run lint
      - name: run test
        run: npm run test
  build-deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: build
        run: npm run build
      - run: |
          echo "Deploying..."
          echo "Deployed"
