name: Matrix Demo
on: workflow-dispatch
jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          # add standalone config
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          #  exclude a particular combination from matrix
          - node-version: 14
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run build
